# fly.toml app configuration file generated for scholaris-backend on 2024-02-09T11:11:43+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scholaris-backend'
primary_region = 'sin'
console_command = '/rails/bin/rails console'

[build]
  dockerfile = "Dockerfile"
  ignorefile = "./dockerignore"

  [build.args]
    USER="admin"
    MODE="development"

[env]
  RAILS_ENV = "development"

[http_service]
  internal_port = 5001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.status]
    port = 5001
    type = 'http'
    interval = '10s'
    timeout = '60s'
    grace_period = '60s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [checks.status.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[statics]]
  guest_path = '/app/backend/public'
  url_prefix = '/'
